DSOFOS/Controllers/tbl_orderUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DSOFOS.Models;
using PagedList;

namespace DSOFOS.Controllers
{
    public class tbl_orderUserController : Controller
    {
        private DSOFOSDBEntities db = new DSOFOSDBEntities();

        public bool IsPostBack { get; private set; }

        // GET: tbl_orderUser
        public ActionResult Index(string Search_Data, string Sorting_Order, string Filter_Value, int? Page_No)
        {
            if (!IsPostBack)
            {
                if (Session["UserId"] == null)
                {
                    Response.Redirect("../User/Login.aspx");
                }

            }
            ViewBag.SortingName = String.IsNullOrEmpty(Sorting_Order) ? "Status" : "";
            if (Search_Data != null)
            {
                Page_No = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }

            ViewBag.FilterValue = Search_Data;

            var orders = from order in db.tbl_order select order;
            if (!String.IsNullOrEmpty(Search_Data))
            {
                orders = orders.Where(order => order.Status.ToUpper().Contains(Search_Data.ToUpper()));
            }

            switch (Sorting_Order)
            {
                case "Status":
                    orders = orders.OrderByDescending(order => order.Status);
                    break;
                case "o_date":
                    orders = orders.OrderByDescending(order => order.o_date);
                    break;
                case "o_unitprice":
                    orders = orders.OrderByDescending(order => order.o_unitprice);
                    break;
                case "MenuItemName":
                    orders = orders.OrderByDescending(order => order.MenuItem.MenuItemName);
                    break;
                case "in_id":
                    orders = orders.OrderByDescending(order => order.tbl_invoice.in_id);
                    break;
                case "UserName":
                    orders = orders.OrderByDescending(order => order.UserMaster.UserName);
                    break;
                default:
                    orders = orders.OrderBy(order => order.Status);
                    break;
            }
            int Size_Of_Page = 10;
            int No_Of_Page = (Page_No ?? 1);

            var tbl_order = db.tbl_order.Include(t => t.MenuItem).Include(t => t.tbl_invoice).Include(t => t.UserMaster);
            return View(orders.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        // GET: tbl_orderUser/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_order tbl_order = db.tbl_order.Find(id);
            if (tbl_order == null)
            {
                return HttpNotFound();
            }
            return View(tbl_order);
        }

        // GET: tbl_orderUser/Create
        public ActionResult Create()
        {
            ViewBag.MenuItemId = new SelectList(db.MenuItems, "MenuItemId", "MenuItemName");
            ViewBag.in_id = new SelectList(db.tbl_invoice, "in_id", "in_id");
            ViewBag.UserId = new SelectList(db.UserMasters, "UserId", "UserName");
            return View();
        }

        // POST: tbl_orderUser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "o_id,MenuItemId,in_id,o_date,o_qty,o_bill,o_unitprice,Status,UserId")] tbl_order tbl_order)
        {
            if (ModelState.IsValid)
            {
                db.tbl_order.Add(tbl_order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MenuItemId = new SelectList(db.MenuItems, "MenuItemId", "MenuItemName", tbl_order.MenuItemId);
            ViewBag.in_id = new SelectList(db.tbl_invoice, "in_id", "in_id", tbl_order.in_id);
            ViewBag.UserId = new SelectList(db.UserMasters, "UserId", "UserName", tbl_order.UserId);
            return View(tbl_order);
        }

        // GET: tbl_orderUser/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_order tbl_order = db.tbl_order.Find(id);
            if (tbl_order == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuItemId = new SelectList(db.MenuItems, "MenuItemId", "MenuItemName", tbl_order.MenuItemId);
            ViewBag.in_id = new SelectList(db.tbl_invoice, "in_id", "in_id", tbl_order.in_id);
            ViewBag.UserId = new SelectList(db.UserMasters, "UserId", "UserName", tbl_order.UserId);
            return View(tbl_order);
        }

        // POST: tbl_orderUser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "o_id,MenuItemId,in_id,o_date,o_qty,o_bill,o_unitprice,Status,UserId")] tbl_order tbl_order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MenuItemId = new SelectList(db.MenuItems, "MenuItemId", "MenuItemName", tbl_order.MenuItemId);
            ViewBag.in_id = new SelectList(db.tbl_invoice, "in_id", "in_id", tbl_order.in_id);
            ViewBag.UserId = new SelectList(db.UserMasters, "UserId", "UserName", tbl_order.UserId);
            return View(tbl_order);
        }

        // GET: tbl_orderUser/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_order tbl_order = db.tbl_order.Find(id);
            if (tbl_order == null)
            {
                return HttpNotFound();
            }
            return View(tbl_order);
        }

        // POST: tbl_orderUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_order tbl_order = db.tbl_order.Find(id);
            db.tbl_order.Remove(tbl_order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DSOFOS/Views/tbl_orderUser/Create.cshtml
@model DSOFOS.Models.tbl_order

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemId, "MenuItemId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuItemId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.in_id, "in_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("in_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.in_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.o_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.o_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.o_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.o_qty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.o_qty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.o_qty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.o_bill, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.o_bill, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.o_bill, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.o_unitprice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.o_unitprice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.o_unitprice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DSOFOS/Views/tbl_orderUser/Delete.cshtml
@model DSOFOS.Models.tbl_order

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.o_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.o_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.o_qty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.o_qty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.o_bill)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.o_bill)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.o_unitprice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.o_unitprice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItem.MenuItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItem.MenuItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_invoice.in_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_invoice.in_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserMaster.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserMaster.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DSOFOS/Views/tbl_orderUser/Details.cshtml
@model DSOFOS.Models.tbl_order

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tbl_order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.o_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.o_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.o_qty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.o_qty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.o_bill)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.o_bill)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.o_unitprice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.o_unitprice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItem.MenuItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItem.MenuItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_invoice.in_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_invoice.in_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserMaster.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserMaster.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.o_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DSOFOS/Views/tbl_orderUser/Edit.cshtml
@model DSOFOS.Models.tbl_order

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.o_id)

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemId, "MenuItemId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuItemId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.in_id, "in_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("in_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.in_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.o_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.o_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.o_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.o_qty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.o_qty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.o_qty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.o_bill, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.o_bill, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.o_bill, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.o_unitprice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.o_unitprice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.o_unitprice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DSOFOS/Views/tbl_orderUser/Index.cshtml
@model PagedList.IPagedList<DSOFOS.Models.tbl_order>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Check Order Status</h2>
@using (Html.BeginForm("Index", "tbl_orderUser", FormMethod.Get))
{
    <p>
        Search Status: @Html.TextBox("Search_Data", ViewBag.FilterValue as string)
        <input type="submit" value="Search" />
    </p>
}


@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table table-striped" id="dtaTable">
    <thead class="dataTableHead">
        <tr>
            <th>
                @Html.ActionLink("o_date", "Index", new { Sorting_Order = ViewBag.SortingName })
                @*@Html.DisplayNameFor(model => model.o_date)*@
            </th>
            <th>
                o_qty
                @*@Html.DisplayNameFor(model => model.o_qty)*@
            </th>
            <th>
                o_bill
                @*@Html.DisplayNameFor(model => model.o_bill)*@
            </th>
            <th>
                @Html.ActionLink("o_unitprice", "Index", new { Sorting_Order = ViewBag.SortingName })
                @*@Html.DisplayNameFor(model => model.o_unitprice)*@
            </th>
            <th>
                @Html.ActionLink("Status", "Index", new { Sorting_Order = ViewBag.SortingName })
                @*@Html.DisplayNameFor(model => model.Status)*@
            </th>
            <th>
                @Html.ActionLink("MenuItemName", "Index", new { Sorting_Order = ViewBag.SortingName })
                @*@Html.DisplayNameFor(model => model.MenuItem.MenuItemName)*@
            </th>
            <th>
                @Html.ActionLink("in_id", "Index", new { Sorting_Order = ViewBag.SortingName })
                @*@Html.DisplayNameFor(model => model.tbl_invoice.in_id)*@
            </th>
            @*<th>
                @Html.ActionLink("UserName", "Index", new { Sorting_Order = ViewBag.SortingName })*@
                @*@Html.DisplayNameFor(model => model.UserMaster.UserName)*@
            @*</th>*@
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.o_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.o_qty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.o_bill)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.o_unitprice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItem.MenuItemName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tbl_invoice.in_id)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.UserMaster.UserName)
            </td>*@
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.o_id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.o_id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.o_id })
                </td>*@
        </tr>
    }

</table>
<script>
    $(document).ready(function () {
        $('#dataTable').DataTable({
            "paging": true,
            "ordering": true,
            "info": true
        });
    });
</script>
<br />
Pages @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, Page_No => Url.Action("Index",
    new { Page_No, Sorting_Order = ViewBag.CurrentSortOrder, Filter_Value = ViewBag.FilterValue }))