DSOFOS/Models/City.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSOFOS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.UserMasters = new HashSet<UserMaster>();
        }
    
        public int CityId { get; set; }
        [Required(ErrorMessage = "Enter CityName")]
        [Display(Name = "CityName")]
        public string CityName { get; set; }
        [Required(ErrorMessage = "Enter CityCode")]
        [Display(Name = "CityCode")]
        public Nullable<int> CityCode { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}

DSOFOS/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DSOFOS.Models;
using PagedList;

namespace DSOFOS.Controllers
{
    public class CitiesController : Controller
    {
        private DSOFOSDBEntities db = new DSOFOSDBEntities();

        // GET: Cities
        public ActionResult Index(string Search_Data, string Sorting_Order, string Filter_Value, int? Page_No)
        {

            ViewBag.SortingName = String.IsNullOrEmpty(Sorting_Order) ? "CityName" : "";
            if (Search_Data != null)
            {
                Page_No = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }

            ViewBag.FilterValue = Search_Data;

            var citys = from city in db.Cities select city;
            if (!String.IsNullOrEmpty(Search_Data))
            {
                citys = citys.Where(city => city.CityName.ToUpper().Contains(Search_Data.ToUpper()));
            }

            switch (Sorting_Order)
            {
                case "CityName":
                    citys = citys.OrderByDescending(city => city.CityName);
                    break;
                case "CityCode":
                    citys = citys.OrderByDescending(city => city.CityCode);
                    break;
                case "StateName":
                    citys = citys.OrderByDescending(city => city.State.StateName);
                    break;
                default:
                    citys = citys.OrderBy(city => city.CityName);
                    break;
            }
            int Size_Of_Page = 5;
            int No_Of_Page = (Page_No ?? 1);


            var cities = db.Cities.Include(c => c.State);
            return View(citys.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName");
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CityId,CityName,CityCode,StateId")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName", city.StateId);
            return View(city);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName", city.StateId);
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CityId,CityName,CityCode,StateId")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName", city.StateId);
            return View(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DSOFOS/Views/Cities/Create.cshtml
@model DSOFOS.Models.City

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_A_DashboardLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateId, "StateId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StateId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DSOFOS/Views/Cities/Delete.cshtml
@model DSOFOS.Models.City

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_A_DashboardLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State.StateName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.StateName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DSOFOS/Views/Cities/Details.cshtml
@model DSOFOS.Models.City

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_A_DashboardLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State.StateName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.StateName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CityId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DSOFOS/Views/Cities/Edit.cshtml
@model DSOFOS.Models.City

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_A_DashboardLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CityId)

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateId, "StateId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StateId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DSOFOS/Views/Cities/Index.cshtml
@model PagedList.IPagedList<DSOFOS.Models.City>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_A_DashboardLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Cities", FormMethod.Get))
{
    <p>
        Search Cities: @Html.TextBox("Search_Data", ViewBag.FilterValue as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table table-striped" id="dtaTable">
    <thead class="dataTableHead">
        <tr>
            <th>
                @Html.ActionLink("CityName", "Index", new { Sorting_Order = ViewBag.SortingName })
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.CityName)
                </th>*@
            <th>
                @Html.ActionLink("CityCode", "Index", new { Sorting_Order = ViewBag.SortingName })
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.CityCode)
                </th>*@
            <th>
                @Html.ActionLink("StateName", "Index", new { Sorting_Order = ViewBag.SortingName })
                @*@Html.DisplayNameFor(model => model.State.StateName)*@
            </th>
            <th>Action</th>
        </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CityName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CityCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State.StateName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.CityId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.CityId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.CityId })
                </td>
            </tr>
        }

</table>
<script>
    $(document).ready(function () {
        $('#dataTable').DataTable({
            "paging": true,
            "ordering": true,
            "info": true
        });
    });
</script>
<br />
Pages @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, Page_No => Url.Action("Index",
    new { Page_No, Sorting_Order = ViewBag.CurrentSortOrder, Filter_Value = ViewBag.FilterValue }))   