DSOFOS/Models/Restaurant.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSOFOS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Categories = new HashSet<Category>();
            this.Orders = new HashSet<Order>();
        }
    
        public int RestaurantId { get; set; }
       // [Required(ErrorMessage = "Enter Restaurant name")]
        public string RestaurantName { get; set; }
        //[Required(ErrorMessage = "Select Category")]
        public Nullable<int> CategoryId { get; set; }
        
        public string RestaurantImage { get; set; }
        //[Required(ErrorMessage = "Enter Description")]
        //[Display(Name = "Description")]
        public string RestaurantDescription { get; set; }
        public bool IsActive { get; set; }
        //[Required(ErrorMessage = "Enter OpenTime")]
        //[Display(Name = "OpenTime")]
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }

        [Required(ErrorMessage = "Choose time")]
        [Display(Name = "StartTime")]
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> startTime { get; set; }
        [Required(ErrorMessage = "Choose time")]
        [Display(Name = "EndTime")]
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> endTime { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}

DSOFOS/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DSOFOS.Models;
using DSOFOS.ViewModel;
using PagedList;

namespace DSOFOS.Controllers
{
    public class RestaurantsController : Controller
    {
        private DSOFOSDBEntities db = new DSOFOSDBEntities();

        public bool IsPostBack { get; private set; }

        // GET: Restaurants
        public ActionResult Index(String Search)
        {
            if (!IsPostBack)
            {
                if (Session["UserId"] == null)
                {
                    Response.Redirect("../User/Login.aspx");
                }
                
            }

            if(Search != null)
            {
                var Result = db.Restaurants.Include(r => r.Category).Where(r => r.RestaurantName.Contains(Search));
                return View(Result);
            }

            var restaurants = db.Restaurants.Include(r => r.Category);
            return View(restaurants.ToList());
        }

        // GET: Restaurants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // GET: Restaurants/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RestaurantId,RestaurantName,CategoryId,RestaurantImage,RestaurantDescription,IsActive,OpenTime,CloseTime")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Restaurants.Add(restaurant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", restaurant.CategoryId);
            return View(restaurant);
        }

        // GET: Restaurants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", restaurant.CategoryId);
            return View(restaurant);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RestaurantId,RestaurantName,CategoryId,RestaurantImage,RestaurantDescription,IsActive,OpenTime,CloseTime")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restaurant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", restaurant.CategoryId);
            return View(restaurant);
        }

        // GET: Restaurants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurant restaurant = db.Restaurants.Find(id);
            db.Restaurants.Remove(restaurant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //public ActionResult ShowMenuRest(int CategoryId)
        //{
        //    IEnumerable<CategoryViewModel> listofMenuItemViewModels = (from objComment in db.Restaurants
        //                                                               where objComment.CategoryId == CategoryId
        //                                                               select new CategoryViewModel()
        //                                                               {


        //                                                                   RestaurantId = objComment.RestaurantId,
        //                                                                   RestaurantName = objComment.RestaurantName,
        //                                                                   RestaurantImage = objComment.RestaurantImage,
        //                                                                   RestaurantDescription = objComment.RestaurantDescription,
        //                                                                   IsActive = objComment.IsActive,
        //                                                                   OpenTime = objComment.OpenTime,
        //                                                                   CloseTime = objComment.CloseTime

        //                                                               }).ToList();
        //    // ViewBag.CategoryId = categoryId;
        //    return View(listofMenuItemViewModels);
        //}
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //public ActionResult ShowMenu(int CategoryId)
        //{
        //    IEnumerable<MenuItemViewModel> listofMenuItemViewModels = (from objComment in db.MenuItems
        //                                                               where objComment.CategoryId == CategoryId
        //                                                               select new MenuItemViewModel()
        //                                                               {


        //                                                                   MenuItemId = objComment.MenuItemId,
        //                                                                   MenuItemName = objComment.MenuItemName,
        //                                                                   MenuItemImage = objComment.MenuItemImage,
        //                                                                   MenuItemDescription = objComment.MenuItemDescription,
        //                                                                   Amount = objComment.Amount,
        //                                                                   IsActive = objComment.IsActive

        //                                                               }).ToList();
        //    // ViewBag.CategoryId = categoryId;
        //    return View(listofMenuItemViewModels);
        //}

        //public ActionResult ShowMenuRest(int RestaurantId)
        //{
        //    IEnumerable<CategoryViewModel> listofMenuItemViewModels = (from objComment in db.Categories
        //                                                               where objComment.RestaurantId == RestaurantId
        //                                                               select new CategoryViewModel()
        //                                                               {


        //                                                                   CategoryId = objComment.CategoryId,
        //                                                                   CategoryName = objComment.CategoryName,
        //                                                                   Image = objComment.Image
                                                                           

        //                                                               }).ToList();
        //    // ViewBag.CategoryId = categoryId;
        //    return View(listofMenuItemViewModels);
        //}

        //public ActionResult AdtocartRest(int? Id)
        //{
        //    MenuItem m = db.MenuItems.Where(x => x.MenuItemId == Id).SingleOrDefault();
        //    return View(m);
        //}

        //List<FoodCartClass> li = new List<FoodCartClass>();

        //[HttpPost]
        //public ActionResult AdtocartRest(MenuItem pi, string qty, int Id)
        //{
        //    MenuItem p = db.MenuItems.Where(x => x.MenuItemId == Id).SingleOrDefault();

        //    FoodCartClass c = new FoodCartClass();
        //    c.ItemId = p.MenuItemId;
        //    c.Amount = (float)p.Amount;
        //    c.Quantity = Convert.ToInt32(qty);
        //    c.Bill = c.Amount * c.Quantity;
        //    c.Status = "Pending";

        //    c.ItemName = p.MenuItemName;
        //    if (TempData["FoodCartClass"] == null)
        //    {
        //        li.Add(c);
        //        TempData["FoodCartClass"] = li;

        //    }
        //    else
        //    {
        //        List<FoodCartClass> li2 = TempData["FoodCartClass"] as List<FoodCartClass>;

DSOFOS/Views/Restaurants/AdtocartRest.cshtml
@model DSOFOS.Models.MenuItem

@{
    ViewBag.Title = "AdtocartRest";
    //Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Add To Cart Lists</h2>

@using (@Html.BeginForm())
    {
        <div class="container">

            <div class="row">

                <div class="col-lg-4 col-md-4 col-sm-4">

                    <img src="~/@Html.DisplayFor(modelItem => Model.MenuItemImage)" alt="" style="width: 200px;height:200px">


                </div>

                <div class="col-lg-8 col-md-8 col-sm-8">

                    <h1>MenuItem Name: @Model.MenuItemName</h1>
                    <h2>Price: @Model.Amount Rs.</h2>
                    <h6>Description: @Model.MenuItemDescription </h6>
                    
                    <input type="number" name="qty" value="1" id="qty" min="1" max="50" />

                    <input type="submit" value="Submit" class="btn btn-primary" />

                </div>



            </div>


        </div>

}

DSOFOS/Views/Restaurants/Create.cshtml
@model DSOFOS.Models.Restaurant

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RestaurantName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestaurantName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RestaurantImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestaurantImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RestaurantDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestaurantDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpenTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CloseTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CloseTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CloseTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DSOFOS/Views/Restaurants/Delete.cshtml
@model DSOFOS.Models.Restaurant

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RestaurantName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RestaurantName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RestaurantImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RestaurantImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RestaurantDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RestaurantDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CloseTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CloseTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DSOFOS/Views/Restaurants/Details.cshtml
@model DSOFOS.Models.Restaurant

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RestaurantName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RestaurantName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RestaurantImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RestaurantImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RestaurantDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RestaurantDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CloseTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CloseTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RestaurantId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DSOFOS/Views/Restaurants/Edit.cshtml
@model DSOFOS.Models.Restaurant

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RestaurantId)

        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RestaurantName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestaurantName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RestaurantImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestaurantImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RestaurantDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestaurantDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpenTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CloseTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CloseTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CloseTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DSOFOS/Views/Restaurants/ShowCategory.cshtml
@model IEnumerable<DSOFOS.ViewModel.CategoryViewModel>
@{
    ViewBag.Title = "ShowCategory";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

@if (TempData["msg"] != null)
{
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Success!</strong> Order
    </div>

}
<!--<table class="table table-striped" id="dtaTable">
       <thead class="dataTableHead">

           <tr>
               <td>
                  item.CategoryName
               </td>
               <td>
                   item.Image
               </td>
               <td>-->
@*<a href='@Url.Action("ShowMenu",new {categoryId = item.CategoryId})'>*@
<!--<input type='button' value='Show Menu' class="btn btn-primary" />
                </a>
            </td>

        </tr>
    </thead>
</table>-->

<div class="row">
 

    <div class="container">
        <h2 class="text-center">Menu Lists</h2>
        @foreach (var item in Model)
        {
            <div class="col-md-4" style="border:2px solid black">
                <div style="text-align:center; border-bottom:2px solid maroon">
                    <h3>@item.CategoryName</h3>
                </div>
                <div>
                    <div class="col-md-8">
                        <img src="~/@Html.DisplayFor(modelItem => item.Image)" alt="" width="100px" height="100px">

                    </div>
                   
                </div>

                

                <div class="col-md-4" style="text-align:right; margin-bottom:10px;border-top:2px solid maroon;padding:2px">
                    @*<input type="button" name="AddToCart" value="Add to Cart" class="btn btn-primary" itemid="@item.MenuItemId" id="btnAddToCart" onclick="AddToCart(this)"/>*@
                    <h4 style="color:#808080; font-family:'Arial Rounded MT';text-align:center">
                        <span class="btn btn-success">
                          
                            @Html.ActionLink("Category", "ShowMenu","RestaurantsList", new { id = @item.CategoryId })
                        </span>
                    </h4>

                    @*<td>
                        @Html.ActionLink("Review", "ShowCategory", new { categoryId = @item.categoryId })
                        <a href='@Url.Action("ShowMenu",new {categoryId = item.CategoryId})'>
                        <input type='button' value='Show Menu' class="btn btn-primary" />
                        </td>*@
                    </div>


                </div>
            }
        </div>

DSOFOS/Views/Restaurants/ShowCommentRest.cshtml
@model IEnumerable<DSOFOS.ViewModel.CommentViewModel>
@{
    ViewBag.Title = "ShowCommentRest";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

<script type="text/javascript">

    function CRateOut(rating) {
        for (var i = 1; i <= rating; i++) {
            $("#span" + i).attr('class', 'glyphicon glyphicon-star-empty');
        }
    }

    function CRateOver(rating) {
        for (var i = 1; i <= rating; i++) {
            $("#span" + i).attr('class', 'glyphicon glyphicon-star');
        }
    }

    function CRateClick(rating) {
        $("#lblRating").val(rating);
        for (var i = 1; i <= rating; i++) {
            $("#span" + i).attr('class', 'glyphicon glyphicon-star');
        }
        for (var i = rating + 1; i <= 5; i++) {
            $("#span" + i).attr('class', 'glyphicon glyphicon-star-empty');
        }
    }

    function CRateSelected() {
        var rating = $("#lblRating").val();
        for (var i = 1; i <= rating; i++) {
            $("#span" + i).attr('class', 'glyphicon glyphicon-star');
        }
    }

    function VerifyRating() {
        var rating = $("#lblRating").val();
        if (rating == "0") {
            alert("Please Select Rating");
            return false;
        }
    }

</script>

<h2>ShowComment</h2>

@foreach (var item in Model)
{
    @Html.Partial("_CommentPartial", item)
}
<h3>Please Enter Your Comment</h3>
@using (Html.BeginForm("AddCommentRest", "Restaurants", FormMethod.Post, new { onsubmit = "return VerifyRating()" }))
{
    <textarea rows="6" cols="50" name="menuComment" id="txtMenuComment"></textarea>
    <div onmouseout="CRateSelected()">
        <span id="span1" onmouseout="CRateOut(1)" onmouseover="CRateOver(1)" onclick="CRateClick(1)" class="glyphicon glyphicon-star-empty"></span>
        <span id="span2" onmouseout="CRateOut(2)" onmouseover="CRateOver(2)" onclick="CRateClick(2)" class="glyphicon glyphicon-star-empty"></span>
        <span id="span3" onmouseout="CRateOut(3)" onmouseover="CRateOver(3)" onclick="CRateClick(3)" class="glyphicon glyphicon-star-empty"></span>
        <span id="span4" onmouseout="CRateOut(4)" onmouseover="CRateOver(4)" onclick="CRateClick(4)" class="glyphicon glyphicon-star-empty"></span>
        <span id="span5" onmouseout="CRateOut(5)" onmouseover="CRateOver(5)" onclick="CRateClick(5)" class="glyphicon glyphicon-star-empty"></span>
    </div>

    <br/> 
    <div>
        <input type="text" name="username" id="lblUserName" placeholder="Enter UserName" />
    </div>

    <div>
        <input type="hidden" name="rating" id="lblRating" value="0" />
    </div>

    <div>
        <input type="hidden" name="menuItemId" id="lblRating" value="@ViewBag.MenuItemId" />
    </div>
    <br />
    <div>
        <input type="submit" class="btn btn-primary active" name="SaveComment" value="Save Comment" />
    </div>

}